#!/bin/bash
set -e

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

deploy_stack() {
    if command_exists terraform && command_exists aws; then
	    set -x
        export application_root_domain=$(cat ./src/.deployment_policy.json |jq -r '.Application | .[].root_domain')
        export deployment_tag=$(cat ./src/.deployment_policy.json |jq -r '.Deployment | .[].tag')
        export deployment_source_code_path=$(cat ./src/.deployment_policy.json |jq -r '.Deployment | .[].source_code_path')
        export aws_s3_bucket_name=$(cat ./src/.deployment_policy.json |jq -r '.AWS | .[].s3_bucket_name')

        terraform init -input=false -force-copy

        terraform plan \
           -var "application_root_domain=$application_root_domain" \
           -var "aws_s3_bucket_name=$aws_s3_bucket_name"  \
           -var "deployment_source_code_path=$deployment_source_code_path" \
           -var "deployment_tag=$deployment_tag" -out "planfile"

        terraform apply -input=false -auto-approve "planfile"
        exit 0
    else
        cat >&2 <<-'EOF'
Error: I'm unable to derermine if your system is configured with terraform and the awscli
EOF
        exit 1
    fi
}

deploy_stack